export default [
    {
        name:'Appointments',
        icon:'mdi-handshake',
        route:'appointments',
    },
    {
        name:'Services',
        icon:'mdi-scale-balance',
        route:'services',
    },
    {
        name:'Requirements',
        icon:'mdi-file-multiple',
        route:'requirements',
    },
    {
        name:'Rating',
        icon:'mdi-star',
        route:'transactions',
    },
    {
        name:'Clients',
        icon:'mdi-account-multiple',
        route:'clients',
    },
    {
        name:'Employees',
        icon:'mdi-account-multiple',
        route:'employees',
    },
]